name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *" # 每天 0:30 时运行，北京时间需要 + 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo # 获取代码分支
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 使用内置的 GITHUB_TOKEN

      - name: Set up Python # 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Configure pip caching # 配置 pip 缓存
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies # 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script # 执行脚本
        run: |
          python main.py

      - name: Check git status
        run: |
          git status

      - name: Commit changes # 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . # 添加所有更改
          git commit -m "Update files by workflow" || echo "No changes to commit"

      - name: Push changes # 推送更改
        run: |
          git push origin master # 确保这里是你想要推送的分支名
